AWSTemplateFormatVersion: 2010-09-09
Description: This template is reusable provisions ec2 instance with default sg on default vpc and default public subnet

# Define Parameters
Parameters:

  MyImageId:  # ImageId 
    Type: String
    Default:  "" # Amazon Linux 2 AMI
    Description:  Enter AMI ID that you want to use

  MyInstanceType: # Instance Type
    Type: String   
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

  SubnetId: # SubnetId
    Type: String
    Default: ""   # it's default public subnet id 
    Description: Enter your Subnet ID 

  MySecGrpId: # Sec Grp Id if you have alredy one
    Type: String 
    Default: ""  # default vpc sg 


  SSHKeyName: # SSH Key Name
    Type: String
    Default: ""
    Description: Enter your SSH-key, make sure you have it in that region
      
  TeamTagKey: # Team Key
    Type: String
    Default: Team
  TeamTagValue:
    Type: String
    Default: Infra
  EnvTagKey:
    Type: String
    Default: Env 
  EnvTagValue:
    Type: String
    Default: Dev   

# Define Resources
Resources: 
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MyImageId 
      InstanceType: !Ref MyInstanceType 
      SubnetId: !Ref SubnetId
      SecurityGroupIds: 
        - !Ref MySecGrpId
      KeyName: !Ref SSHKeyName
      Tags: 
        - Key: Name
          Value: EC2Name
        - Key: !Ref TeamTagKey
          Value: !Ref TeamTagValue
        - Key: !Ref EnvTagKey
          Value: !Ref  EnvTagValue 
      
# Define Outputs
Outputs: 
  InstancePublicIp: 
    Value: !GetAtt MyInstance.PublicIp