AWSTemplateFormatVersion: 2010-09-09
Description: This template provisions a multiple s3 buckets

## Parameters 

Parameters:

  MyBucketName:
    Type: String 
    Default: ''
    Description: Enter your bucket name
  MyBucketName2:
    Type: String 
    Default: ''  
  TeamValue:
    Type: String
    Default: "dev"
    Description: Enter 
  OwnerValue: 
    Type: String
    Default: ""
    Description: Enter your name
  S3Versioning:
    Type: String
    Default: "Enabled"
    AllowedValues:
      - Enabled
      - Suspended

## Resources

Resources: 

  # S3 bucket 1
  MyS3Bucket: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref MyBucketName
      VersioningConfiguration: 
        Status: !Ref S3Versioning
      Tags: 
      - Key: Team
        Value:  !Ref TeamValue
      - Key: Owner
        Value: !Ref OwnerValue

  # S3 bucket 2
  MyS3Bucket2: 
    DependsOn:
    - MyS3Bucket
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref MyBucketName2
      VersioningConfiguration: 
        Status: !Ref S3Versioning
      Tags: 
      - Key: Team
        Value:  !Ref TeamValue
      - Key: Owner
        Value: !Ref OwnerValue

## Outputs

Outputs: 

  SampleBucketName: 
    Description: S3 bucket name
    Value:  !Ref MyS3Bucket
  SampleBucketName2: 
    Description: S3 bucket name and region
    Value:  
      Fn::Join:
      - ''
      - - 'bucket:'
        - Ref: AWS::Region
        - ':'
        - Ref: MyS3Bucket2
