AWSTemplateFormatVersion: 2010-09-09
Description: Creates ELB with a EC2 Target Group Associated
### Define Parameters
Parameters:
  MyTgName:
    Type: String
    Default: "MyTargetGroup"  
  MyALBName: 
    Type: String
    Default: "MyALB"
  ELBSecurityGroupId: 
    Type: String
    Default: ""  
  MyEc2InstanceId: 
    Type: String
    Default: ""   
  MyVPC:
    Type: String
    Default: ""  
  PublicSubnet1:
    Type: String
    Default: ""
  PublicSubnet2:
    Type: String
    Default: ""  
  AppLoadbalancerSslCertArn:
    Description: Enter your SSL certificate for Application load balancer
    Type: String
    Default: "" 
    

### Define Resouces 
Resources:
 
  EC2TargetGroup: # Target Group
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: 
      - MyALB
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      Port: 80
      HealthCheckPort: "traffic-port"
      Protocol: HTTP
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      HealthCheckEnabled: true
      TargetType: instance
      Targets:
      - Id:
          Ref: WordpressWebInstanceId
      Matcher:
        HttpCode: '200'
      Name: !Ref TGName 
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      VpcId: !Ref MyVPC
      Tags:
      - Key: Name
        Value: EC2TargetGroup
      - Key: Port
        Value: 80

  myHTTPSlListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
      - CertificateArn:
          Ref: AppLoadbalancerSslCertArn
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref EC2TargetGroup
      LoadBalancerArn: !Ref MyALB
      Port: '443'
      Protocol: HTTPS

  myHTTPListener: 
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - MyALB
      - EC2TargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupARN:
            Ref: EC2TargetGroup
      LoadBalancerARN:
          Ref: MyALB
      Port: 80
      Protocol: HTTP

  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing # or internal
      Subnets:
      - Ref: PublicSubnet1
      - Ref: PublicSubnet2
      SecurityGroups:
      - Ref: ELBSecurityGroupId      
      

Outputs:
  myELBDNSName:
    Description: 'Webserver ELB DNS Name A Record'
    Value:
      !GetAtt MyALB.DNSName
  EC2TargetGroup:
    Description: 'My EC2 Target Group'
    Value:
      Ref: MyALBName
  MyLoadBalancerArn:
    Description: 'Application Load Balancer'
    Value:
      Ref: MyALB       