AWSTemplateFormatVersion: 2010-09-09
Description: This Template Creates a VPC with  

Parameters:
  NetworkStackName:
    Description: "Name of an active CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack."
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: (^[a-zA-Z][-a-zA-Z0-9]*$)
    Default: "" #vpc

  SSHKeyName:
    Description: 'Name of the EC2-key you need to use for Bastion Instance'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: ""
  SSHLocation:
    Description: must be a valid IP CIDR range of the form x.x.x.x/x.
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
  InstanceType: 
    Description: Choose a valid Instance Type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium]

Mappings:
  AWSInstanceType2Arch:    
    t2.micro:
      Arch : HVM64  
    t2.small: 
      Arch : HVM64  
    t2.medium:  
      Arch : HVM64

  AWSRegionArch2AMI:
    us-east-1: 
      HVM64: ami-04d29b6f966df1537 
    us-east-2: 
      HVM64: ami-09558250a3419e7d0

Resources:
  EC2BastionInstance:   
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ AWSRegionArch2AMI, !Ref 'AWS::Region' , !FindInMap [ AWSInstanceType2Arch, !Ref InstanceType, Arch ] ]  
      KeyName: !Ref SSHKeyName
      InstanceType: !Ref InstanceType
      SubnetId: 
        Fn::ImportValue:
          Fn::Sub: '${NetworkStackName}-PubicSubnet1ID'
      SecurityGroupIds: 
        - Fn::ImportValue:
            Fn::Sub: '${NetworkStackName}-BastionSecurityGroupID'
      Tags:
      - Key: Name
        Value: BastionHost